import js from "@eslint/js";
import tseslint from "typescript-eslint";

/**
 * Root ESLint configuration (flat config).
 *
 * Scope is deliberately narrow: the repository currently contains only the
 * database toolchain (prisma/seed.ts, prisma.config.ts). Applications under
 * apps/* will extend this config with their own framework rules once they
 * exist — this file should stay free of React or NestJS specifics.
 *
 * The type-aware rule sets (recommendedTypeChecked) are intentionally not
 * enabled: they require a tsconfig.json project reference, which does not exist
 * yet. Add them together with the first application.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/.next/**",
      "**/coverage/**",
      // Generated by `prisma generate`; never hand-edited.
      "**/generated/**",
      "storage/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
    },
    rules: {
      // Unused arguments are common in callbacks and adapters; allow them when
      // explicitly marked with a leading underscore.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // coding_standards.md: "Avoid any. Strong typing is mandatory."
      "@typescript-eslint/no-explicit-any": "error",
      // coding_standards.md: "Never swallow exceptions. Never ignore errors."
      "no-empty": ["error", { allowEmptyCatch: false }],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "prefer-const": "error",
      "no-var": "error",
    },
  },

  {
    // The seed script and Prisma config are operator tooling: console output is
    // their user interface, not a debugging leftover.
    files: ["prisma/seed.ts", "prisma.config.ts"],
    rules: {
      "no-console": "off",
    },
  },
);
