import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import tseslint from "typescript-eslint";

/**
 * Root ESLint configuration (flat config).
 *
 * Framework-specific rules are scoped to the application they belong to, in
 * blocks at the end of this file, so a rule for one app can never quietly
 * apply to another. Everything above those blocks holds for the whole
 * repository.
 *
 * The type-aware rule sets (recommendedTypeChecked) are intentionally not
 * enabled: they require a tsconfig.json project reference, which does not exist
 * yet. Add them together with the first application.
 */
export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/.next/**",
      "**/coverage/**",
      // Generated by `prisma generate`; never hand-edited.
      "**/generated/**",
      // Regenerated by Next on every build, and it must not be edited.
      "**/next-env.d.ts",
      "storage/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
    },
    rules: {
      // Unused arguments are common in callbacks and adapters; allow them when
      // explicitly marked with a leading underscore.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // coding_standards.md: "Avoid any. Strong typing is mandatory."
      "@typescript-eslint/no-explicit-any": "error",
      // coding_standards.md: "Never swallow exceptions. Never ignore errors."
      "no-empty": ["error", { allowEmptyCatch: false }],
      eqeqeq: ["error", "always", { null: "ignore" }],
      "prefer-const": "error",
      "no-var": "error",
    },
  },

  {
    /**
     * Build configuration runs in Node before any bundler is involved, so it
     * legitimately reads `process`. Declared here rather than globally because
     * application code should not reach for the process environment directly —
     * it goes through validated configuration.
     */
    files: ["**/*.config.{js,mjs,ts}"],
    languageOptions: {
      globals: { process: "readonly", __dirname: "readonly" },
    },
  },

  {
    // The seed script and Prisma config are operator tooling: console output is
    // their user interface, not a debugging leftover.
    files: ["prisma/seed.ts", "prisma.config.ts"],
    rules: {
      "no-console": "off",
    },
  },

  {
    /**
     * React rules, scoped to the frontend.
     *
     * The Rules of Hooks are correctness rules, not style: a conditional hook
     * or a stale dependency produces a bug that renders fine and behaves wrong.
     * They apply only here, which keeps this file free of framework specifics
     * for everything else, as intended above.
     */
    files: ["apps/frontend/**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
);
